### ISSUE TITLE
No diagrams overlap selections. Nothing to process.

### ISSUE THREAD

**Issue by i2000s** [evandrocoan/PlantUmlDiagrams#12]
I got this error (see title) after installed PlantUNM plugin. Both the latest version and an earlier version (3.28?) of GraphViz has been tried. Local `GRAPHVIZ_DOT` and `GRAPHVIZ_HOME` had been set up correctly. I have also put the `plantuml.jar`  somewhere as a trial. Output of console is below (see `file not exist` error):

```
reloading plugin ShellScript.ShellScript
reloading plugin jvantuyl-sublime_diagram_plugin-37ba88c.diagram_plugin
reloading plugin sublime_diagram_plugin.diagram_plugin
plugins loaded
error: Error trying to parse settings: Invalid escape in Packages\sublime_diagram_plugin\Diagram.sublime-settings:8:17
Viewer Setting: Preview
Loading processor class: <class 'jvantuyl-sublime_diagram_plugin-37ba88c.diagram.plantuml.PlantUMLProcessor'>
Detected 'C:\\Users\\q00471279\\AppData\\Roaming\\Sublime Text 3\\Packages\\jvantuyl-sublime_diagram_plugin-37ba88c\\diagram\\plantuml-8024.jar'
Version Detection:
b'PlantUML version 8024 (Sun May 03 23:05:11 CST 2015)\r\n(GPL source distribution)\r\nOpenJDK Runtime Environment\r\nOpenJDK 64-Bit Server VM\r\n1.8.0_262-Huawei_JDK_V100R001C00SPC262B001-b10\r\nWindows 10\r\n\r\nThe environment variable GRAPHVIZ_DOT has been set to ?D:\\App\\GraphViz\\bin\\dot.exe\r\nDot executable is ?D:\\App\\GraphViz\\bin\\dot.exe\r\nError: file does not exist\r\nError: only sequence diagrams will be generated\r\n'
PlantUML Smoke Check:
b'The environment variable GRAPHVIZ_DOT has been set to ?D:\\App\\GraphViz\\bin\\dot.exe\r\nDot executable is ?D:\\App\\GraphViz\\bin\\dot.exe\r\nError: file does not exist\r\nError: only sequence diagrams will be generated\r\n'
Unable to load processor: <class 'jvantuyl-sublime_diagram_plugin-37ba88c.diagram.plantuml.PlantUMLProcessor'>
Traceback (most recent call last):
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\jvantuyl-sublime_diagram_plugin-37ba88c\diagram\__init__.py", line 44, in setup
    proc.load()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\jvantuyl-sublime_diagram_plugin-37ba88c\diagram\plantuml.py", line 90, in load
    self.check_plantuml_functionality()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\jvantuyl-sublime_diagram_plugin-37ba88c\diagram\plantuml.py", line 121, in check_plantuml_functionality
    raise Exception('PlantUML does not appear functional')
Exception: PlantUML does not appear functional
error: Unable to load diagram plugin, check console for details.
Traceback (most recent call last):
  File "D:\App\Sublime\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\jvantuyl-sublime_diagram_plugin-37ba88c\diagram_plugin.py", line 26, in plugin_loaded
    setup()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\jvantuyl-sublime_diagram_plugin-37ba88c\diagram\__init__.py", line 51, in setup
    raise Exception('No working processors found!')
Exception: No working processors found!
Viewer Setting: Preview
Loading processor class: <class 'sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor'>
Detected 'C:\\Users\\q00\\AppData\\Roaming\\Sublime Text 3\\Packages\\sublime_diagram_plugin\\diagram\\plantuml.1.2018.1.jar'
Version Detection:
b'PlantUML version 1.2018.01 (Mon Jan 29 02:08:22 CST 2018)\r\n(GPL source distribution)\r\nJava Runtime: OpenJDK Runtime Environment\r\nJVM: OpenJDK 64-Bit Server VM\r\nJava Version: 1.8.0_262-Huawei_JDK_V100R001C00SPC262B001-b10\r\nOperating System: Windows 10\r\nOS Version: 10.0\r\nDefault Encoding: GBK\r\nLanguage: zh\r\nCountry: CN\r\nMachine: DESKTOP-3BFQ3FH\r\nPLANTUML_LIMIT_SIZE: 4096\r\nProcessors: 12\r\nMax Memory: 7,583,301,632\r\nTotal Memory: 512,753,664\r\nFree Memory: 504,699,720\r\nUsed Memory: 8,053,944\r\nThread Active Count: 1\r\n\r\nThe environment variable GRAPHVIZ_DOT has been set to ?D:\\App\\GraphViz\\bin\\dot.exe\r\nDot executable is ?D:\\App\\GraphViz\\bin\\dot.exe\r\nError: File does not exist\r\nError: only sequence diagrams will be generated\r\n'
PlantUML Smoke Check:
b'The environment variable GRAPHVIZ_DOT has been set to ?D:\\App\\GraphViz\\bin\\dot.exe\r\nDot executable is ?D:\\App\\GraphViz\\bin\\dot.exe\r\nError: File does not exist\r\nError: only sequence diagrams will be generated\r\n'
Unable to load processor: <class 'sublime_diagram_plugin.diagram.plantuml.PlantUMLProcessor'>
Traceback (most recent call last):
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\sublime_diagram_plugin\diagram\__init__.py", line 45, in setup
    proc.load()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\sublime_diagram_plugin\diagram\plantuml.py", line 121, in load
    self.check_plantuml_functionality()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\sublime_diagram_plugin\diagram\plantuml.py", line 153, in check_plantuml_functionality
    raise Exception('PlantUML does not appear functional')
Exception: PlantUML does not appear functional
error: Unable to load diagram plugin, check console for details.
Traceback (most recent call last):
  File "D:\App\Sublime\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\sublime_diagram_plugin\diagram_plugin.py", line 26, in plugin_loaded
    setup()
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\sublime_diagram_plugin\diagram\__init__.py", line 52, in setup
    raise Exception('No working processors found!')
Exception: No working processors found!
Processing diagrams in <sublime.View object at 0x000001BD57C59160>...
error: No diagrams overlap selections.

Nothing to process.
```

?

**Comment by evandrocoan** [comment]
Looks like you installed another package. My package is named `PlantUmlDiagrams`, but on you stacktraces I see names like `sublime_diagram_plugin` and `jvantuyl-sublime_diagram_plugin-37ba88c`.

How are you installing this package?

**Comment by i2000s** [comment]
Sorry, the error log above was exported from installing the original toolchain. Using this repo's version, I got the following error log. By reading the code, it seems to be halted at the setup stage. No server was setup. Any idea? 

```
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin PlantUmlDiagrams.diagram_plugin
Traceback (most recent call last):
  File "D:\App\Sublime\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\q00\AppData\Roaming\Sublime Text 3\Packages\PlantUmlDiagrams\diagram_plugin.py", line 15, in <module>
    import plantuml_connection
ImportError: No module named 'plantuml_connection'
plugins loaded
```

**Comment by evandrocoan** [comment]
It did not found a required dependency.

You can see the list of dependencies on https://github.com/evandrocoan/PlantUmlDiagrams/blob/master/dependencies.json

Usually, Package Control should install them for you.

What is your Sublime Text version?
