### ISSUE TITLE
missing dependencies error - Sublime Text 4

### ISSUE THREAD

**Issue by mbrick02** [evandrocoan/PlantUmlDiagrams#17]
The package is working but since I installed it I've been getting a Package Control error: "2 missing dependencies were just installed.  Sublime Text should be restarted..."

I updated to "Sublime Text 4" a month ago.

I've restarted a few times but still get the error.

not sure if this matters but I used plantuml.com, plantuml-1.2023.10.jar for "jar_file" in
Preferences > Package Settings > PlantUMLDiagrams > Settings -  User:
...
```
// The full path to the plantuml.jar file
`"jar_file": "C:\Users\mb\plantUML\plantuml-1.2023.10.jar",
```
...

here is my complete console with the dependency errors at the end:
```
DPI mode: per-monitor v2
startup, version: 4152 windows x64 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
application: /C/Program Files/Sublime Text
working dir: /C/Program Files/Sublime Text
packages path: /C/Users/Owner/AppData/Roaming/Sublime Text/Packages
state path: /C/Users/Owner/AppData/Roaming/Sublime Text/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/Owner/AppData/Roaming/Sublime Text/Installed Packages
ignored_packages: ["GitGutter", "sublimelint", "Vintage"]
pre session restore time: 0.476062
startup time: 0.542062
first paint time: 0.601062
git: using configuration from C:\Program Files\Git\cmd\git.exe
git: tracking working dir C:\wamp64\www\sandbox\onnotknowing
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading python 3.3 plugin 0_package_control_loader.-backrefs
reloading plugin Default.open_in_browser
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
reloading plugin Default.pane
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
reloading plugin Default.paragraph
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\0_package_control_loader.sublime-package\-backrefs.py", line 1, in <module>
ImportError: No module named 'package_control'
reloading python 3.3 plugin 0_package_control_loader.-mdpopups
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
reloading plugin Default.paste_from_history
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
reloading plugin Default.profile
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
reloading plugin Default.quick_panel
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\0_package_control_loader.sublime-package\-mdpopups.py", line 1, in <module>
reloading plugin Default.rename
ImportError: No module named 'package_control'
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading python 3.3 plugin 0_package_control_loader.01-pygments
reloading plugin Default.settings
reloading python 3.3 plugin 0_package_control_loader.01-sublime_lib
reloading plugin Default.show_scope_name
reloading python 3.3 plugin 0_package_control_loader.08-portalockerfile
reloading plugin Default.side_bar
reloading python 3.3 plugin 0_package_control_loader.09-concurrentloghandler
reloading plugin Default.sort
reloading python 3.3 plugin 0_package_control_loader.10-debugtools
reloading python 3.3 plugin 0_package_control_loader.50-markupsafe
reloading plugin Default.switch_file
reloading python 3.3 plugin 0_package_control_loader.50-pathlib
reloading python 3.3 plugin 0_package_control_loader.50-plantumlconnection
reloading python 3.3 plugin 0_package_control_loader.50-pymdownx
reloading python 3.3 plugin 0_package_control_loader.50-python-markdown
reloading python 3.3 plugin 0_package_control_loader.50-python-pywin32
reloading plugin win32com
reloading plugin win32
reloading plugin win32/lib
reloading plugin win32comext
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading plugin Default.symbol
reloading python 3.3 plugin 0_package_control_loader.51-python-jinja2
reloading python 3.3 plugin BracketHighlighter.bh_core
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
reloading plugin A File Icon.plugin
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\BracketHighlighter.sublime-package\bh_core.py", line 16, in <module>
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\BracketHighlighter.sublime-package\bh_rules.py", line 7, in <module>
ImportError: cannot import name bre
reloading python 3.3 plugin BracketHighlighter.bh_logging
reloading python 3.3 plugin BracketHighlighter.bh_plugin
reloading python 3.3 plugin BracketHighlighter.bh_popup
reloading python 3.3 plugin BracketHighlighter.bh_regions
reloading python 3.3 plugin BracketHighlighter.bh_remove
reloading python 3.3 plugin BracketHighlighter.bh_rules
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\BracketHighlighter.sublime-package\bh_rules.py", line 7, in <module>
ImportError: cannot import name bre
reloading python 3.3 plugin BracketHighlighter.bh_search
reloading python 3.3 plugin BracketHighlighter.bh_swapping
reloading python 3.3 plugin BracketHighlighter.bh_wrapping
reloading python 3.3 plugin BracketHighlighter.support
reloading python 3.3 plugin Color Highlight.ColorHighlight
reloading python 3.3 plugin Color Highlight.colorizer
reloading python 3.3 plugin Color Highlight.colors
reloading python 3.3 plugin Color Highlight.settings
reloading python 3.3 plugin Emmet.emmet-plugin
reloading python 3.3 plugin Git.git_commands
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin Package Reloader.Package Reloader
reloading python 3.3 plugin PackageDev._logging
reloading python 3.3 plugin PackageDev.main
reloading python 3.3 plugin Phpcs.phpcs
reloading python 3.3 plugin PlantUmlDiagrams.diagram_plugin
reloading python 3.3 plugin SideBarEnhancements.SideBar
reloading python 3.3 plugin SideBarEnhancements.SideBarAPI
reloading python 3.3 plugin SideBarEnhancements.SideBarDefaultDisable
reloading python 3.3 plugin Xdebug Client.main
reloading python 3.3 plugin ayu-master.activation
reloading python 3.3 plugin ayu-master.Icons
reloading python 3.3 plugin ColorPicker.sublimecp
reloading python 3.3 plugin concurrentloghandler.setup
reloading python 3.3 plugin debugtools.setup
reloading python 3.3 plugin JSHint Gutter.JSHint
reloading python 3.3 plugin plantumlconnection.setup
reloading python 3.3 plugin portalockerfile.setup
plugins loaded
Package Control: Installing 2 missing dependencies
reloading settings Packages/mdpopups/Preferences.sublime-settings
C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/loader.py:294: UserWarning: Duplicate name: '-mdpopups.py'
Package Control: Installed missing dependency mdpopups
C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/loader.py:294: UserWarning: Duplicate name: '-backrefs.py'
Package Control: Installed missing dependency backrefs
Package Control: No updated packages
error: Package Control

2 missing dependencies were just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```

**Comment by evandrocoan** [comment]
Hi. Given:
```` 
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\0_package_control_loader.sublime-package\-backrefs.py", line 1, in <module>
````

Can you try to close Sublime Text and delete the file `C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\0_package_control_loader.sublime-package`?

When Sublime Text starts again, it will recreate it for you; after it is re-recreated, you can try restarting Sublime Text and see how things go.

The problem looks like the dependency '-backrefs.py' uses an invalid dependency number.

My package does not require this '-backrefs.py' dependency, only these:
```
{
    "windows": {
        ">3000": [
            "python-pywin32",
            "portalockerfile",
            "concurrentloghandler",
            "debugtools",
            "plantumlconnection"
        ]
    },
    "*": {
        "*": [
            "portalockerfile",
            "concurrentloghandler",
            "debugtools",
            "plantumlconnection"
        ]
    }
}
```

You can also see my fork of package control, where I did rewrite a few things about dependency management to see if, in my version, this dependency problem is fixed: https://github.com/evandrocoan/PackagesManager

**Comment by mbrick02** [comment]
It remakes the file, but then I get the same error.  The console looks the same.

    On Friday, September 1, 2023 at 10:18:27 PM EDT, evandrocoan ***@***.***> wrote:  
 
 


Hi. Given:
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\0_package_control_loader.sublime-package\-backrefs.py", line 1, in <module>

Can you try to close Sublime Text and delete the file C:\Users\Owner\AppData\Roaming\Sublime Text\Installed Packages\0_package_control_loader.sublime-package?

When Sublime Text starts again, it will recreate it for you; after it is re-recreated, you can try restarting Sublime Text and see how things go.

The problem looks like the dependency '-backrefs.py' uses an invalid dependency number.

My package does not require this '-backrefs.py' dependency, only these:
{
    "windows": {
        ">3000": [
            "python-pywin32",
            "portalockerfile",
            "concurrentloghandler",
            "debugtools",
            "plantumlconnection"
        ]
    },
    "*": {
        "*": [
            "portalockerfile",
            "concurrentloghandler",
            "debugtools",
            "plantumlconnection"
        ]
    }
}

You can also see my fork of package control, where I did rewrite a few things about dependency management to see if, in my version, this dependency problem is fixed: https://github.com/evandrocoan/PackagesManager

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by evandrocoan** [comment]
There is a problem with these two dependencies; package control is not detecting. Your file should look like this, but yours, instead of `50-backrefs.py` has only `-backrefs.py`. You can try uninstalling the packages that require those dependencies.
![image](https://github.com/evandrocoan/PlantUmlDiagrams/assets/5332158/5206fdc4-a8ac-4621-91e5-58598f08c40f)

**Comment by mbrick02** [comment]
Is there and easy and reliable way to list which packages need those dependencies?

    On Monday, September 4, 2023 at 07:49:38 PM EDT, evandrocoan ***@***.***> wrote:  
 
 


There is a problem with these two dependencies; package control is not detecting. Your file should look like this, but yours, instead of 50-backrefs.py has only -backrefs.py. You can try uninstalling the packages that require those dependencies.


—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by evandrocoan** [comment]
You unzip all packages inside `Installed Packages` and search inside all `dependencies.json` files to see if they have said dependency. Also, searches for the already unzipped packages are already on the `Packages` directory. Other than that, you can twinkle with the Package Control code which is doing exactly this to install the missing dependencies.

These are packages I got installed and are using those:
* mdpopups
  1. Packages\ApplySyntax\dependencies.json:
  1. Packages\BracketHighlighter\dependencies.json:
  1. Packages\ColorHelper\dependencies.json:
  1. Packages\ExportHtml\dependencies.json:
  1. Packages\GitGutter\dependencies.json:
  1. Packages\HexViewer\dependencies.json:
  1. Packages\LaTeXTools\dependencies.json:
  1. Packages\LSP\dependencies.json:
  1. Packages\ScopeHunter\dependencies.json:
  1. Packages\StudioChannel\package_control_channel\repository\dependencies.json:
  1. Packages\TabsExtra\dependencies.json:

* backrefs
  1. Packages\BracketHighlighter\dependencies.json
  1. Packages\LSP\dependencies.json
  1. Packages\StudioChannel\package_control_channel\repository\dependencies.json

**Comment by mbrick02** [comment]
I uninstalled BracketHighlighter,
deleted  ..Sublime Text\Installed Packages\
0_package_control_loader.sublime-package
restarted twice and it seems to be working.
 and it seems to be working.
Thanks so much!
