### ISSUE TITLE
Problem loading plugin on linux

### ISSUE THREAD

**Issue by francislavoie** [evandrocoan/PlantUmlDiagrams#2]
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "diagram_plugin in /home/flavoie/.config/sublime-text-3/Installed Packages/PlantUmlDiagrams.sublime-package", line 1
    ﻿
    ^
SyntaxError: invalid character in identifier
```

Also for your Portalocker, gives a problem:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/flavoie/.config/sublime-text-3/Packages/PortalockerFiles/setup.py", line 6, in <module>
    import setuptools
ImportError: No module named 'setuptools'
```

Any other info I should provide? I just tried to install via Package Control and this is what I get.

Version: Sublime Dev 3159

**Comment by danmacnaughtan** [comment]
I am getting the same issue on macOS (10.13.3)
Sublime version 3.0, Build 3143
Also installed via Package Control.

**Comment by evandrocoan** [comment]
Thanks for reporting it. I hope I can fix it. I just pushed a few updates here in hope this problem will be fixed. You guys need to wait until the updates are released by the packagecontrol.io web site.

**Comment by francislavoie** [comment]
Nice, worked for me. Got this output though

```
22:50:10:398.721457 1.15e+01 - PlantUmlDiagrams.process_diagram_image:34 - Processing diagrams in /home/flavoie/[snip].txt...
Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 939, in emit
  File "./python3.3/logging/__init__.py", line 810, in format
  File "./python3.3/logging/__init__.py", line 548, in format
  File "./python3.3/logging/__init__.py", line 311, in getMessage
TypeError: not all arguments converted during string formatting
Logged from file PlantUmlDiagrams.sublime-package, line 44
22:50:10:425.111055 1.15e+01 - PlantUmlDiagrams.diagram.plantuml.generate:101 - Failed to connect to the server: <urlopen error [Errno 111] Connection refused> (http://localhost:8080/plantuml/) Falling back to local rendering...
decode image failed
22:50:12:508.341551 1.36e+01 - PlantUmlDiagrams.diagram.render_and_view:195 - Sublime 3 Simple Viewer viewing ['/home/flavoie/[snip].png']
```

Not sure if that's a TypeError you care about.

**Comment by evandrocoan** [comment]
Thanks, I should fix this TypeError some time in the future. For now, it seems to be causing trouble.
